### ISSUE TITLE
Strong/bold

### ISSUE THREAD

**Issue by DutchPete** [gammons/base16-obsidian#1]
In your theme CSS you have:
```css
.cm-strong, .markdown-preview-view em {
  color: var(--base09);
}
```

It does not work for Preview, you want:
```css
strong,
.cm-strong {
  color: var(--base09);
}
```
